name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cargo watch
      run: cargo install cargo-watch
    - name: Build
      run: cargo start
    - name: Run tests
      run: cargo test --verbose
